
service: titanium-lambda

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 512
  timeout: 6
  endpointType: EDGE

  region: us-east-1

package:
  include:
  - node_modules/**

  exclude:
#    - exclude-me-dir/**

functions:
  Lambda:
    handler: index.handler

plugins:
  - serverless-offline
