
service: titanium-lambda

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 512
  timeout: 6
  endpointType: EDGE

  region: us-east-1

package:
  include:
  - node_modules/**

  exclude:
#    - exclude-me-dir/**

functions:
  Lambda:
    handler: index.handler
    events:
      - http:    
          path: /
          method: options
          cors: true
      - http:
          path: /
          method: get
          cors: true

plugins:
  - serverless-offline
