AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members

Resources:
  Lambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join ['-', ['fw', !Ref 'ProjectId']]
      Handler: index.handler
      Runtime: nodejs8.10
      MemorySize: 512
      Timeout: 120
      AutoPublishAlias: Latest
      Environment:
        Variables:
          NODE_ENV: production
      Role: arn:aws:iam::xxx:role/Worker-Lambda

  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Derp
      DefinitionBody:
        swagger: "2.0"
        info:
          version: "1.0"
          title: [!Ref 'ProjectId']
        host: "i4r9f0ntaf.execute-api.us-east-2.amazonaws.com"
        basePath: "/Stage"
        schemes:
        - "https"
        paths:
          /starwars-char-data:
            get:
              responses:
                "200":
                  description: "200 response"
              security:
              - api_key: []
              x-amazon-apigateway-integration:
                uri: !Join ['arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:xxx:function:', [!Ref 'ProjectId'], '/invocations']
                passthroughBehavior: "when_no_match"
                httpMethod: "GET"
                type: "aws_proxy"

            post:
              responses:
                "200":
                  description: "200 response"
              security:
              - api_key: []
              x-amazon-apigateway-integration:
                'arn:aws:iam::133345006009:role/FW-Worker-Lambda'
                uri: !Join ['arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:xxx:function:', [!Ref 'ProjectId'], '/invocations']
                passthroughBehavior: "when_no_match"
                httpMethod: "POST"
                type: "aws_proxy"
            options:
              responses:
                "200":
                  description: "200 response"
              x-amazon-apigateway-integration:
                uri: !Join ['arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:xxx:function:', [!Ref 'ProjectId'], '/invocations']
                passthroughBehavior: "when_no_match"
                httpMethod: "POST"
                type: "aws_proxy"
        securityDefinitions:
          api_key:
            type: "apiKey"
            name: "x-api-key"
            in: "header"
